name: Nathaniel Lash
bio: >-
  <p>I'm a <a href='https://www.propublica.org/people/nat-lash'>developer and reporter</a> on ProPublica's News Applications team, where I cover infectious diseases and agriculture.
  I work on pieces that require novel analysis and data pipelines, as well as interactive graphics that break down complicated concepts and engage readers.</p>
  <p>Before ProPublica, I was a <a href='https://www.nytimes.com/by/nathaniel-lash'>graphics reporter/editor</a> with the New York Times Opinion section.</p>
  <p> In my spare time, you can find me picking out bluegrass tunes on the mandolin or walking a bass line on the upright. You can send me an <a href='mailto:nathaniel.lash@gmail.com'>email</a> or I'm at natlash.99 on Signal.
resume: /static/nathaniel-lash-resume.pdf
